//-----------------------------------------------------------------------------
//
//       ###    ###   #####   #########   ########    ###    ###  ###   ###
//        #      #      #      #      #    #      #    #      #    #     #
//        #      #      #      #   #       #      #    #      #     #   #
//        ########      #      #####       #######     #      #      ###
//        #      #      #      #   #       #     #     #      #     #   #
//        #      #      #      #      #    #      #    #      #    #     #
//       ###    ###   #####   #########   ###      #    ######    ###   ###
//
// Verilog Netlist:
// Generated at: Thu Sep 12 17:44:15 2024
// This file is automatically generated by Verilog Exporter
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2B2_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2B2_140_90D2(VS, Z, A1, GS, A2N);
	input VS;
	output Z;
	input A1;
	input GS;
	input A2N;

	assign Z = (~A2N & A1);

endmodule // SC_AND2B2_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2B2_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2B2_140_90D4(VS, Z, A1, A2N, GS);
	input VS;
	output Z;
	input A1;
	input A2N;
	input GS;

	assign Z = (~A2N & A1);

endmodule // SC_AND2B2_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2_50_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2_50_30(Z, VS, A1, GS, A2);
	output Z;
	input VS;
	input A1;
	input GS;
	input A2;

	assign Z = (A1 & A2);

endmodule // SC_AND2_50_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2_100_40
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2_100_40(Z, VS, A2, A1, GS);
	output Z;
	input VS;
	input A2;
	input A1;
	input GS;

	assign Z = (A1 & A2);

endmodule // SC_AND2_100_40


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2_100_90(Z, VS, A2, A1, GS);
	output Z;
	input VS;
	input A2;
	input A1;
	input GS;

	assign Z = (A1 & A2);

endmodule // SC_AND2_100_90

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2_140_80(Z, VS, A1, A2, GS);
	output Z;
	input VS;
	input A1;
	input A2;
	input GS;

	assign Z = (A1 & A2);

endmodule // SC_AND2_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2_140_90D2(VS, Z, GS, A2, A1);
	input VS;
	output Z;
	input GS;
	input A2;
	input A1;

	assign Z = (A1 & A2);

endmodule // SC_AND2_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND2_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND2_140_90D4(VS, Z, A2, A1, GS);
	input VS;
	output Z;
	input A2;
	input A1;
	input GS;

	assign Z = (A1 & A2);

endmodule // SC_AND2_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND3B1_120_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND3B1_120_70(VS, Z, A3, A2, GS, A1N);
	input VS;
	output Z;
	input A3;
	input A2;
	input GS;
	input A1N;

	assign Z = (~A1N & A2 & A3);

endmodule // SC_AND3B1_120_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND3B1_130_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND3B1_130_80(Z, VS, A1N, GS, A3, A2);
	output Z;
	input VS;
	input A1N;
	input GS;
	input A3;
	input A2;

	assign Z = (~A1N & A2 & A3);

endmodule // SC_AND3B1_130_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND3B12_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND3B12_140_90D4(VS, Z, A1N, A2N, A3, GS);
	input VS;
	output Z;
	input A1N;
	input A2N;
	input A3;
	input GS;

	assign Z = (~(A1N | A2N) & A3);

endmodule // SC_AND3B12_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND3_50_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND3_50_30(Z, VS, GS, A3, A2, A1);
	output Z;
	input VS;
	input GS;
	input A3;
	input A2;
	input A1;

	assign Z = (A1 & A2 & A3);

endmodule // SC_AND3_50_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND3_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND3_140_80(Z, VS, A3, A2, GS, A1);
	output Z;
	input VS;
	input A3;
	input A2;
	input GS;
	input A1;

	assign Z = (A1 & A2 & A3);

endmodule // SC_AND3_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND4B1_140_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND4B1_140_70(Z, VS, A1N, GS, A3, A2, A4);
	output Z;
	input VS;
	input A1N;
	input GS;
	input A3;
	input A2;
	input A4;

	assign Z = (~A1N & A2 & A3 & A4);

endmodule // SC_AND4B1_140_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND4B34_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND4B34_140_80(VS, Z, A3N, A2, A4N, A1, GS);
	input VS;
	output Z;
	input A3N;
	input A2;
	input A4N;
	input A1;
	input GS;

	assign Z = (~A3N & ~A4N & A1 & A2);

endmodule // SC_AND4B34_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AND4_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AND4_140_80(VS, Z, A4, A3, A1, A2, GS);
	input VS;
	output Z;
	input A4;
	input A3;
	input A1;
	input A2;
	input GS;

	assign Z = (A1 & A2 & A3 & A4);

endmodule // SC_AND4_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO12_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO12_140_80(Z, VS, A, B1, B2, GS);
	output Z;
	input VS;
	input A;
	input B1;
	input B2;
	input GS;

	assign Z = ((B1 & B2) | A);

endmodule // SC_AO12_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO13_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO13_140_80(Z, VS, B3, B2, A, B1, GS);
	output Z;
	input VS;
	input B3;
	input B2;
	input A;
	input B1;
	input GS;

	assign Z = ((B1 & B2 & B3) | A);

endmodule // SC_AO13_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO22_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO22_140_80(VS, Z, A1, B1, A2, B2, GS);
	input VS;
	output Z;
	input A1;
	input B1;
	input A2;
	input B2;
	input GS;

	assign Z = ((B1 & B2) | (A1 & A2));

endmodule // SC_AO22_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO22_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO22_140_90D2(VS, Z, A2, A1, B1, B2, GS);
	input VS;
	output Z;
	input A2;
	input A1;
	input B1;
	input B2;
	input GS;

	assign Z = ((A1 & A2) | (B1 & B2));

endmodule // SC_AO22_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO112_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO112_140_80(C2, C1, B, A, Z, VS, GS);
	input C2;
	input C1;
	input B;
	input A;
	output Z;
	input VS;
	input GS;
	

	assign Z = ((C1 & C2) | B | A);

endmodule // SC_AO112_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO112_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO112_140_90D2(C2, C1, B, A, Z, VS, GS);
	input C2;
	input C1;
	input B;
	input A;
	output Z;
	input VS;
	input GS;
	

	assign Z = ((C1 & C2) | B | A);

endmodule // SC_AO112_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO112_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO112_140_90D4(C2, C1, B, A, Z, VS, GS);
	input C2;
	input C1;
	input B;
	input A;
	output Z;
	input VS;
	input GS;
	

	assign Z = ((C1 & C2) | B | A);

endmodule // SC_AO112_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AO122_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AO122_140_80(A, B1, B2, C1, C2, Z, VS, GS);
    input VS;
    input GS;
    input A;
    input B1;
    input B2;
    input C1;
    input C2;
    output Z;

    assign  Z = A | (B1 & B2) | (C1 & C2);

endmodule // SC_AO122_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AOA112_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AOA112_140_80(VS, Z, B, C1, C2, A, GS);
	input VS;
	output Z;
	input B;
	input C1;
	input C2;
	input A;
	input GS;

	assign Z = (A & (B | (C1 & C2)));

endmodule // SC_AOA112_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AOI12_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AOI12_140_90D2(VS, ZN, A, B1, B2, GS);
	input VS;
	output ZN;
	input A;
	input B1;
	input B2;
	input GS;

	assign ZN = ~(A | (B1 & B2));

endmodule // SC_AOI12_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AOI12_E100_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AOI12_E100_70(VS, ZN, B2, B1, A, GS);
	input VS;
	output ZN;
	input B2;
	input B1;
	input A;
	input GS;

	assign ZN = ~(A | (B1 & B2));

endmodule // SC_AOI12_E100_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AOI22_E100_60
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AOI22_E100_60(VS, ZN, A2, A1, B1, B2, GS);
	input VS;
	output ZN;
	input A2;
	input A1;
	input B1;
	input B2;
	input GS;

	assign ZN = ~((A1 & A2) | (B1 & B2));

endmodule // SC_AOI22_E100_60


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_AOI112_E100_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_AOI112_E100_70(C2, C1, B, A, ZN, GS, VS);
	input C2;
	input C1;
	input B;
	input A;
	output ZN;
	input GS;
	input VS;

	assign ZN = ~(B | A | (C1 & C2));

endmodule // SC_AOI112_E100_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_40_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_40_30(VS, Z, A, GS);
	input VS;
	output Z;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_40_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_100_50
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_100_50(Z, VS, GS, A);
	output Z;
	input VS;
	input GS;
	input A;

	assign Z = A;

endmodule // SC_BUF_100_50


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_100_90(Z, VS, A, GS);
	output Z;
	input VS;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_100_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_100_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_100_90D4(Z, VS, A, GS);
	output Z;
	input VS;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_100_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_130_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_130_80(VS, Z, A, GS);
	input VS;
	output Z;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_130_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_130_80S1
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_130_80S1(Z, VS, A, GS);
	output Z;
	input VS;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_130_80S1


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140X2_100
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140X2_100(VS, Z, A, GS);
	input VS;
	output Z;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_140X2_100


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140_60
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140_60(VS, Z, A, GS);
	input VS;
	output Z;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_140_60


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140_100
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140_100(Z, VS, GS, A);
	output Z;
	input VS;
	input GS;
	input A;

	assign Z = A;

endmodule // SC_BUF_140_100


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140_100D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140_100D2(VS, Z, GS, A);
	input VS;
	output Z;
	input GS;
	input A;

	assign Z = A;

endmodule // SC_BUF_140_100D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140_100D3
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140_100D3(Z, VS, GS, A);
	output Z;
	input VS;
	input GS;
	input A;

	assign Z = A;

endmodule // SC_BUF_140_100D3


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140_100D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140_100D4(VS, Z, GS, A);
	input VS;
	output Z;
	input GS;
	input A;

	assign Z = A;

endmodule // SC_BUF_140_100D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_BUF_140_100D8
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_BUF_140_100D8(VS, Z, A, GS);
	input VS;
	output Z;
	input A;
	input GS;

	assign Z = A;

endmodule // SC_BUF_140_100D8


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_CARRY_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_CARRY_140_80(CO, VS, B, CI, GS, A);
	output CO;
	input VS;
	input B;
	input CI;
	input GS;
	input A;

	assign CO = (A & B)|(A & CI)|(B & CI);

endmodule // SC_CARRY_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_DFB_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_DFB_140_90(CDN, CP, D, GS, Q, QN, SDN, VS);
    input CDN;
    input CP;
    input D;
    input GS;
    output Q;
    output QN;
    input SDN;
    input VS;

	reg    Q_reg;
        
    always @(posedge CP or negedge SDN or negedge CDN) begin
       	if (!CDN) begin
           	Q_reg <= 1'b0;
       	end
       	else if (!SDN) begin
           	Q_reg <= 1'b1;
       	end  
       	else begin
           	Q_reg <= D;
       	end
    end
       
	assign   Q  =  Q_reg;
	assign   QN = ~Q_reg;

endmodule  // SC_DFB_140_90

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_DFC_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_DFC_140_90(CDN, CP, D, GS, Q, QN, VS);
    input CDN;
    input CP;
    input D;
    input GS;
    output Q;
    output QN;
    input VS;

	reg    Q_reg;

    always @(posedge CP or negedge CDN) begin
        if (!CDN) begin
            Q_reg <= 1'b0;
        end
        else begin
            Q_reg <= D;
        end
    end
        
	assign   Q  =  Q_reg;
	assign  QN = ~Q_reg;

endmodule  // SC_DFC_140_90

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_DFS_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_DFS_140_90(CP, D, GS, Q, QN, SDN, VS);
    input CP;
    input D;
    input GS;
    output Q;
    output QN;
    input SDN;
    input VS;

	reg    Q_reg;

    always @(posedge CP or negedge SDN) begin
        if (!SDN) begin
            Q_reg <= 1'b1;
        end
        else begin
            Q_reg <= D;
        end
    end
        
	assign   Q  =  Q_reg;
	assign   QN = ~Q_reg;

endmodule  // SC_DFS_140_90

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_FNCLOCKGATING_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_FNCLOCKGATING_140_80(OEN, CP, D, GS, Q,VS);
input OEN;
input CP;
input D;
input GS;
output Q;
input VS;

reg Q_reg;

wire A;
assign A = (OEN | D);

always @(CP or A)begin
  if (!CP)begin
  Q_reg <= A;
  end
end

assign Q = (Q_reg & CP);
  
endmodule

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_HADD_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_HADD_140_80(CO, VS, SUM, A, B, GS);
	output CO;
	input VS;
	output SUM;
	input A;
	input B;
	input GS;

	assign CO = (A & B);
	assign SUM = ((B | A) & ~(A & B));

endmodule // SC_HADD_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_50_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_50_30(ZN, VS, A, GS);
	output ZN;
	input VS;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_50_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_100_50
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_100_50(ZN, VS, A, GS);
	output ZN;
	input VS;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_100_50


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_100_90(ZN, VS, A, GS);
	output ZN;
	input VS;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_100_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_100_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_100_90D2(VS, ZN, A, GS);
	input VS;
	output ZN;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_100_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_140_60
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_140_60(ZN, VS, A, GS);
	output ZN;
	input VS;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_140_60


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_140_100
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_140_100(ZN, VS, GS, A);
	output ZN;
	input VS;
	input GS;
	input A;

	assign ZN = ~A;

endmodule // SC_INV_140_100


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_140_100D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_140_100D2(VS, ZN, A, GS);
	input VS;
	output ZN;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_140_100D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_140_100D3
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_140_100D3(ZN, VS, A, GS);
	output ZN;
	input VS;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_140_100D3


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_INV_140_100D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_INV_140_100D4(VS, ZN, A, GS);
	input VS;
	output ZN;
	input A;
	input GS;

	assign ZN = ~A;

endmodule // SC_INV_140_100D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_LAC_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_LAC_140_80(CDN, CP, D, GS, Q, VS);
    input CDN;
    input CP;
    input D;
    input GS;
    output Q;
    input VS;

	reg    Q_reg;

    always @(CP or CDN or D) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else if (CP) begin
        Q_reg <= D;
      end
    end
   
	assign Q = Q_reg;

endmodule  // SC_LAC_140_80

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_LAC_140_80S1
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_LAC_140_80S1(CDN, CPN, D, GS, Q, VS);
    input CDN;
    input CPN;
    input D;
    input GS;
    output Q;
    input VS;

	reg    Q_reg;

    always @(CPN or CDN or D) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else if (!CPN) begin
        Q_reg <= D;
      end
    end
   
	assign   Q = Q_reg;

endmodule  // SC_LAC_140_80S1

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_LAS_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_LAS_140_80(CP, D, GS, Q, SD, VS);
    input CP;
    input D;
    input GS;
    output Q;
    input SD;
    input VS;

	reg    Q_reg;
        
    always @(CP or SD or D) begin
			if (SD) begin
				Q_reg <= 1'b1;
			end
			else if (CP) begin
				Q_reg <= D;
			end
    end
   
	assign   Q = Q_reg;

endmodule  // SC_LAS_140_80

//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MFB_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MFB_140_80(CDN, CP, D0, D1, GS, Q, S, SDN, VS);
    input CDN;
    input CP;
    input D0;
    input D1;
    input GS;
    output Q;
    input S;
    input SDN;
    input VS;

    reg    Q_reg;
        
    wire D;
    
    assign   D = S ? D1 : D0;
    
    always @(posedge CP or negedge SDN or negedge CDN) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else if (!SDN) begin
        Q_reg <= 1'b1;
      end
      else begin
        Q_reg <= D;
      end
    end
    
    assign  Q  = Q_reg;


endmodule


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MFC_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MFC_140_80(CDN, CP, D0, D1, GS, Q, S, VS);
    input CDN;
    input CP;
    input D0;
    input D1;
    input GS;
    output Q;
    input S;
    input VS;

    reg    Q_reg;
    
    wire D;
    
    assign   D = S ? D1 : D0;
    
    always @(posedge CP or negedge CDN) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else begin
        Q_reg <= D;
      end
    end
    
    assign   Q  =  Q_reg;


endmodule


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MFC_140_80S1
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MFC_140_80S1(CDN, CPN, D0, D1, GS, Q, S, VS);
    input CDN;
    input CPN;
    input D0;
    input D1;
    input GS;
    output Q;
    input S;
    input VS;

    reg    Q_reg;
    
    wire D;
    
    assign   D = S ? ~D1 : ~D0;
    
    always @(negedge CPN or negedge CDN) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else begin
        Q_reg <= ~D;
      end
    end
    
    assign   Q  =  Q_reg;


endmodule


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MFC_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MFC_140_90D4(CDN, CP, D0, D1, GS, Q, S, VS);
    input CDN;
    input CP;
    input D0;
    input D1;
    input GS;
    output Q;
    input S;
    input VS;

    reg    Q_reg;
    
    wire D;
    
    assign   D = S ? D1 : D0;
    
    always @(posedge CP or negedge CDN) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else begin
        Q_reg <= D;
      end
    end
    
    assign   Q  =  Q_reg;


endmodule


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MFS_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MFS_140_80(CP, D0, D1, GS, Q, S, SDN,VS);
    input CP;
    input D0;
    input D1;
    input GS;
    output Q;
    input S;
    input SDN;
    input VS;

    reg    Q_reg;
    
    wire D;
    
    assign   D = S ? ~D1 : ~D0;
    
    always @(posedge CP or negedge SDN) begin
      if (!SDN) begin
        Q_reg <= 1'b1;
      end
      else begin
        Q_reg <= ~D;
      end
    end
    
    assign   Q  =  Q_reg;


endmodule


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MX21_100_50
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MX21_100_50(VS, Z, A0N, S, GS, A1N);
	input VS;
	output Z;
	input A0N;
	input S;
	input GS;
	input A1N;

	assign Z = (S ? ~A1N : ~A0N);

endmodule // SC_MX21_100_50


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MX21_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MX21_140_80(VS, Z, A0, S, A1, GS);
	input VS;
	output Z;
	input A0;
	input S;
	input A1;
	input GS;

	assign Z = (S ? A1 : A0);

endmodule // SC_MX21_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MX21_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MX21_140_90(VS, Z, A0, S, GS, A1);
	input VS;
	output Z;
	input A0;
	input S;
	input GS;
	input A1;

	assign Z = (S ? A1 : A0);

endmodule // SC_MX21_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_MX21_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_MX21_140_90D2(VS, Z, A0, S, A1, GS);
	input VS;
	output Z;
	input A0;
	input S;
	input A1;
	input GS;

	assign Z = (S ? A1 : A0);

endmodule // SC_MX21_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2B1_30_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2B1_30_30(ZN, VS, A2, GS, A1N);
	output ZN;
	input VS;
	input A2;
	input GS;
	input A1N;

	assign ZN = ~(~A1N & A2);

endmodule // SC_NAND2B1_30_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2B1_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2B1_140_90(VS, ZN, A2, GS, A1N);
	input VS;
	output ZN;
	input A2;
	input GS;
	input A1N;

	assign ZN = ~(~A1N & A2);

endmodule // SC_NAND2B1_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2B2_140X2_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2B2_140X2_90(VS, ZN, A1, GS, A2N);
	input VS;
	output ZN;
	input A1;
	input GS;
	input A2N;

	assign ZN = ~(~A2N & A1);

endmodule // SC_NAND2B2_140X2_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2B2_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2B2_140_90(VS, ZN, A1, A2N, GS);
	input VS;
	output ZN;
	input A1;
	input A2N;
	input GS;

	assign ZN = ~(~A2N & A1);

endmodule // SC_NAND2B2_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2B12_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2B12_140_80(VS, ZN, A2N, A1N, GS);
	input VS;
	output ZN;
	input A2N;
	input A1N;
	input GS;

	assign ZN = ~(~A1N & ~A2N);

endmodule // SC_NAND2B12_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_30_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_30_30(VS, ZN, A2, GS, A1);
	input VS;
	output ZN;
	input A2;
	input GS;
	input A1;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_30_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_70_40
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_70_40(VS, ZN, A1, A2, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input GS;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_70_40


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_100_90(VS, ZN, A1, A2, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input GS;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_100_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_140X2_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_140X2_90(VS, ZN, A1, A2, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input GS;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_140X2_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_140X3_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_140X3_80(VS, ZN, A2, A1, GS);
	input VS;
	output ZN;
	input A2;
	input A1;
	input GS;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_140X3_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_140_90(VS, ZN, A2, A1, GS);
	input VS;
	output ZN;
	input A2;
	input A1;
	input GS;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND2_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND2_140_90D2(VS, ZN, A2, GS, A1);
	input VS;
	output ZN;
	input A2;
	input GS;
	input A1;

	assign ZN = ~(A1 & A2);

endmodule // SC_NAND2_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND3B3_120_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND3B3_120_90(VS, ZN, A3N, A2, GS, A1);
	input VS;
	output ZN;
	input A3N;
	input A2;
	input GS;
	input A1;

	assign ZN = ~(~A3N & A1 & A2);

endmodule // SC_NAND3B3_120_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND3B12_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND3B12_140_90(VS, ZN, A3, A1N, A2N, GS);
	input VS;
	output ZN;
	input A3;
	input A1N;
	input A2N;
	input GS;

	assign ZN = ~(~(A1N | A2N) & A3);

endmodule // SC_NAND3B12_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND3_50_40
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND3_50_40(VS, ZN, A3, GS, A2, A1);
	input VS;
	output ZN;
	input A3;
	input GS;
	input A2;
	input A1;

	assign ZN = ~(A1 & A2 & A3);

endmodule // SC_NAND3_50_40


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND3_120_100
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND3_120_100(ZN, VS, A1, A2, A3, GS);
	output ZN;
	input VS;
	input A1;
	input A2;
	input A3;
	input GS;

	assign ZN = ~(A1 & A2 & A3);

endmodule // SC_NAND3_120_100


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND3_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND3_140_90D4(VS, ZN, A1, A2, A3, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input A3;
	input GS;

	assign ZN = ~(A1 & A2 & A3);

endmodule // SC_NAND3_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND4B1_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND4B1_100_90(VS, ZN, A1N, A4, A3, A2, GS);
	input VS;
	output ZN;
	input A1N;
	input A4;
	input A3;
	input A2;
	input GS;

	assign ZN = ~(~A1N & A2 & A3 & A4);

endmodule // SC_NAND4B1_100_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND4B34_120_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND4B34_120_90(ZN, VS, A1, A2, A4N, GS, A3N);
	output ZN;
	input VS;
	input A1;
	input A2;
	input A4N;
	input GS;
	input A3N;

	assign ZN = ~(~A4N & ~A3N & A1 & A2);

endmodule // SC_NAND4B34_120_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND4B34_120_90S1
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND4B34_120_90S1(ZN, VS, A1, A2, A3N, GS, A4N);
	output ZN;
	input VS;
	input A1;
	input A2;
	input A3N;
	input GS;
	input A4N;

	assign ZN = ~(~A3N & ~A4N & A1 & A2);

endmodule // SC_NAND4B34_120_90S1


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NAND4_120_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NAND4_120_90(VS, ZN, A1, A2, A3, A4, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input A3;
	input A4;
	input GS;

	assign ZN = ~(A1 & A2 & A3 & A4);

endmodule // SC_NAND4_120_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2B2_120_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2B2_120_70(ZN, VS, A1, A2N, GS);
	output ZN;
	input VS;
	input A1;
	input A2N;
	input GS;

	assign ZN = (~A1 & A2N);

endmodule // SC_NOR2B2_120_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2B2_140_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2B2_140_70(ZN, VS, A1, GS, A2N);
	output ZN;
	input VS;
	input A1;
	input GS;
	input A2N;

	assign ZN = (~A1 & A2N);

endmodule // SC_NOR2B2_140_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2_30_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2_30_30(ZN, VS, A1, A2, GS);
	output ZN;
	input VS;
	input A1;
	input A2;
	input GS;

	assign ZN = ~(A1 | A2);

endmodule // SC_NOR2_30_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2_100_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2_100_30(VS, ZN, A2, GS, A1);
	input VS;
	output ZN;
	input A2;
	input GS;
	input A1;

	assign ZN = ~(A2 | A1);

endmodule // SC_NOR2_100_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2_100_90(ZN, VS, A1, GS, A2);
	output ZN;
	input VS;
	input A1;
	input GS;
	input A2;

	assign ZN = ~(A1 | A2);

endmodule // SC_NOR2_100_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2_140_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2_140_70(VS, ZN, A2, A1, GS);
	input VS;
	output ZN;
	input A2;
	input A1;
	input GS;

	assign ZN = ~(A2 | A1);

endmodule // SC_NOR2_140_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2_140_90(VS, ZN, A1, A2, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input GS;

	assign ZN = ~(A1 | A2);

endmodule // SC_NOR2_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR2_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR2_140_90D2(VS, ZN, A2, A1, GS);
	input VS;
	output ZN;
	input A2;
	input A1;
	input GS;

	assign ZN = ~(A1 | A2);

endmodule // SC_NOR2_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR3B3_100_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR3B3_100_30(VS, ZN, A3N, A2, A1, GS);
	input VS;
	output ZN;
	input A3N;
	input A2;
	input A1;
	input GS;

	assign ZN = (~(A2 | A1) & A3N);

endmodule // SC_NOR3B3_100_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR3B3_130_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR3B3_130_80(VS, ZN, A3N, A2, GS, A1);
	input VS;
	output ZN;
	input A3N;
	input A2;
	input GS;
	input A1;

	assign ZN = (~(A1 | A2) & A3N);

endmodule // SC_NOR3B3_130_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR3_30_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR3_30_30(ZN, VS, A1, A2, GS, A3);
	output ZN;
	input VS;
	input A1;
	input A2;
	input GS;
	input A3;

	assign ZN = ~(A1 | A2 | A3);

endmodule // SC_NOR3_30_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR3_100_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR3_100_30(VS, ZN, A3, A2, A1, GS);
	input VS;
	output ZN;
	input A3;
	input A2;
	input A1;
	input GS;

	assign ZN = ~(A2 | A1 | A3);

endmodule // SC_NOR3_100_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR3_130_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR3_130_70(VS, ZN, A3, A2, GS, A1);
	input VS;
	output ZN;
	input A3;
	input A2;
	input GS;
	input A1;

	assign ZN = ~(A3 | A1 | A2);

endmodule // SC_NOR3_130_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_NOR4B34_130_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_NOR4B34_130_80(ZN, VS, A1, A2, GS, A4N, A3N);
	output ZN;
	input VS;
	input A1;
	input A2;
	input GS;
	input A4N;
	input A3N;

	assign ZN = (~A1 & ~A2 & A3N & A4N);

endmodule // SC_NOR4B34_130_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OA12_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OA12_140_80(Z, VS, A, B1, GS, B2);
	output Z;
	input VS;
	input A;
	input B1;
	input GS;
	input B2;

	assign Z = (A & (B2 | B1));

endmodule // SC_OA12_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OA12_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OA12_140_90D2(VS, Z, A, B1, GS, B2);
	input VS;
	output Z;
	input A;
	input B1;
	input GS;
	input B2;

	assign Z = (A & (B1 | B2));

endmodule // SC_OA12_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OA13_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OA13_140_80(Z, VS, B3, B2, B1, GS, A);
	output Z;
	input VS;
	input B3;
	input B2;
	input B1;
	input GS;
	input A;

	assign Z = (A & (B3 | B1 | B2));

endmodule // SC_OA13_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OA22_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OA22_140_80(Z, VS, A1, A2, B1, B2, GS);
	output Z;
	input VS;
	input A1;
	input A2;
	input B1;
	input B2;
	input GS;

	assign Z = ((A2 | A1) & (B2 | B1));

endmodule // SC_OA22_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OA122_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OA122_140_80(VS, Z, C2, B2, C1, A, B1, GS);
	input VS;
	output Z;
	input C2;
	input B2;
	input C1;
	input A;
	input B1;
	input GS;

	assign Z = (A & (B2 | B1) & (C2 | C1));

endmodule // SC_OA122_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OA211_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OA211_140_80(Z, VS, B, C, A2, GS, A1);
	output Z;
	input VS;
	input B;
	input C;
	input A2;
	input GS;
	input A1;

	assign Z = (B & C & (A2 | A1));

endmodule // SC_OA211_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OAI12_100_E80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OAI12_100_E80(VS, ZN, B2, B1, GS, A);
	input VS;
	output ZN;
	input B2;
	input B1;
	input GS;
	input A;

	assign ZN = ~(A & (B2 | B1));

endmodule // SC_OAI12_100_E80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OAI22_100_E80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OAI22_100_E80(VS, ZN, B1, A1, A2, B2, GS);
	input VS;
	output ZN;
	input B1;
	input A1;
	input A2;
	input B2;
	input GS;

	assign ZN = ~((A1 | A2) & (B1 | B2));

endmodule // SC_OAI22_100_E80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OAI211_90_E60
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OAI211_90_E60(ZN, VS, A1, A2, C, B, GS);
	output ZN;
	input VS;
	input A1;
	input A2;
	input C;
	input B;
	input GS;

	assign ZN = ~(B & C & (A1 | A2));

endmodule // SC_OAI211_90_E60


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OAO112_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OAO112_140_80(Z, VS, A, B, C1, GS, C2);
	output Z;
	input VS;
	input A;
	input B;
	input C1;
	input GS;
	input C2;

	assign Z = (A | (B & (C1 | C2)));

endmodule // SC_OAO112_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR2B2_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR2B2_140_90D4(VS, Z, A1, GS, A2N);
	input VS;
	output Z;
	input A1;
	input GS;
	input A2N;

	assign Z = ~(~A1 & A2N);

endmodule // SC_OR2B2_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR2_30_30
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR2_30_30(VS, Z, A1, GS, A2);
	input VS;
	output Z;
	input A1;
	input GS;
	input A2;

	assign Z = ~(~A1 & ~A2);

endmodule // SC_OR2_30_30


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR2_100_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR2_100_90(VS, Z, A1, GS, A2);
	input VS;
	output Z;
	input A1;
	input GS;
	input A2;

	assign Z = ~(~A1 & ~A2);

endmodule // SC_OR2_100_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR2_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR2_140_80(VS, Z, A1, A2, GS);
	input VS;
	output Z;
	input A1;
	input A2;
	input GS;

	assign Z = ~(~A2 & ~A1);

endmodule // SC_OR2_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR2_140_90D2
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR2_140_90D2(VS, Z, A2, A1, GS);
	input VS;
	output Z;
	input A2;
	input A1;
	input GS;

	assign Z = ~(~A2 & ~A1);

endmodule // SC_OR2_140_90D2


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR2_140_90D4
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR2_140_90D4(VS, Z, A2, A1, GS);
	input VS;
	output Z;
	input A2;
	input A1;
	input GS;

	assign Z = ~(~A2 & ~A1);

endmodule // SC_OR2_140_90D4


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR3_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR3_140_80(VS, Z, A1, A2, A3, GS);
	input VS;
	output Z;
	input A1;
	input A2;
	input A3;
	input GS;

	assign Z = (A1 | A3 | A2);

endmodule // SC_OR3_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR4B1_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR4B1_140_90(VS, Z, A1N, A2, A4, GS, A3);
	input VS;
	output Z;
	input A1N;
	input A2;
	input A4;
	input GS;
	input A3;

	assign Z = (~A1N | A2 | A3 | A4);

endmodule // SC_OR4B1_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_OR4_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_OR4_140_90(VS, Z, A3, A2, A4, A1, GS);
	input VS;
	output Z;
	input A3;
	input A2;
	input A4;
	input A1;
	input GS;

	assign Z = (A1 | A4 | A3 | A2);

endmodule // SC_OR4_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_REGCELL_140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_REGCELL_140_90(Q, HOLD, D0, D1, S, CPN, CDN, VS, GS);
    output Q;
    input HOLD;
    input D0;
    input D1;
    input S;
    input CPN;
    input CDN;
    input VS;
    input GS;

	reg    Q_reg;
    
    wire A;
	wire B;

    
    assign   A = HOLD ? Q_reg: D0;
    assign   B = S ? D1 :A;
    
    always @(negedge CPN or negedge CDN) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else begin
        Q_reg <= B;
      end
    end
    
    assign   Q  =  Q_reg;

endmodule // SC_REGCELL_140_90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_REGCELL_140_90S1
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_REGCELL_140_90S1(Q, HOLD, D0, D1, S, CP, CDN, VS, GS);
    output Q;
    input HOLD;
    input D0;
    input D1;
    input S;
    input CP;
    input CDN;
    input VS;
    input GS;

	reg    Q_reg;
    
    wire A;
	wire B;

    
    assign   A = HOLD ? Q_reg : D0;
    assign   B = S ? D1 : A;
    
    always @(posedge CP or negedge CDN) begin
      if (!CDN) begin
        Q_reg <= 1'b0;
      end
      else begin
        Q_reg <= B;
      end
    end
    
    assign   Q  =  Q_reg;

endmodule // SC_REGCELL_140_90S1


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_XNOR2_E120_E70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_XNOR2_E120_E70(VS, ZN, A1, A2, GS);
	input VS;
	output ZN;
	input A1;
	input A2;
	input GS;

	assign ZN = ~(A1 ^ A2);

endmodule // SC_XNOR2_E120_E70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_XNOR3_140_E90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_XNOR3_140_E90(VS, ZN, A2, A3, A1, GS);
	input VS;
	output ZN;
	input A2;
	input A3;
	input A1;
	input GS;

	assign ZN = ~((A1 ^ A2) ^ A3);

endmodule // SC_XNOR3_140_E90


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_XOR2_140_80
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_XOR2_140_80(VS, Z, A2, A1, GS);
	input VS;
	output Z;
	input A2;
	input A1;
	input GS;

	assign Z = (A2 ^ A1);

endmodule // SC_XOR2_140_80


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_XOR2_E120_70
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_XOR2_E120_70(VS, Z, A2, A1, GS);
	input VS;
	output Z;
	input A2;
	input A1;
	input GS;

	assign Z = (A1 ^ A2);

endmodule // SC_XOR2_E120_70


//-----------------------------------------------------------------------------
// Library Name: HCQ_2404150_SC_LIB_SCH
// Cell Name: SC_XOR3_E140_90
// View Name: netlist
//-----------------------------------------------------------------------------
module SC_XOR3_E140_90(VS, Z, A3, A2, A1, GS);
	input VS;
	output Z;
	input A3;
	input A2;
	input A1;
	input GS;

	assign Z = ((A1 ^ A2) ^ A3);

endmodule // SC_XOR3_E140_90
